ARG AL_TAG
FROM amazon/aws-for-fluent-bit:runtime-debug-init-al${AL_TAG}

# Only last CMD command will be executed, automatically replaces the original entrypoint
CMD /init/fluent_bit_init_process; chmod +x /init/invoke_fluent_bit.sh; cd /cores; /init/invoke_fluent_bit.sh; echo "Waiting 2 minutes for EFS core file transfers"; sleep 120